version: "2"
services:
  db:
    image: eccube/postgres
    environment:
      - POSTGRES_USER=cube3_dev_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cube3_dev
  eccube3:
    build:
      args:
        - DBTYPE=pgsql
  codecept:
    build:
      args:
        - DBTYPE=pgsql
