version: "2"
services:
  eccube3:
    ports:
      - "8080:80"
      - "8443:443"
  browser:
    ports:
      - "5900:5900"
    environment:
      - SCREEN_WIDTH=1680
      - SCREEN_HEIGHT=1050
  mailcatcher:
    ports:
      - "1080:1080"
      - "1025:1025"
