version: "2"
services:
  eccube3:
    build:
      args:
        - DIRTYPE=subdir
        - ECCUBE_PATH=/var/www/html/ec-cube
    environment:
      - ECCUBE_ROOT_URLPATH=/ec-cube
  codecept:
    environment:
      - BASE_URL=http://eccube3/ec-cube/