version: "2"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eccube_db
      - MYSQL_USER=eccube_user
      - MYSQL_PASSWORD=password
  eccube3:
    build:
      args:
        - DBTYPE=mysql
  codecept:
    build:
      args:
        - DBTYPE=mysql
