version: "2"
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=cube3_dev_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cube3_dev
  eccube3:
    build:
      context: eccube3
      args:
        - ECCUBE_BRANCH=master
        - ECCUBE_REPOS=https://github.com/EC-CUBE/ec-cube.git
    environment:
      - PGPASSWORD=password
      - POSTGRES_ENV_POSTGRES_PASSWORD=password
    ports:
      - 80
    links:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped
  codecept:
    build:
      context: codeception
      args:
        - ECCUBE_BRANCH=master
        - ECCUBE_REPOS=https://github.com/EC-CUBE/ec-cube.git
    depends_on:
      - phantomjs
      - eccube3
    volumes:
      - ./tests:/project/tests
      - ./codeception.yml:/project/codeception.yml
  phantomjs:
    image: edvakf/phantomjs-japanese
    command: --webdriver=0.0.0.0:4444
    ports:
      - 5900
