actor: Tester
coverage:
    enabled: true
    remote: true
    c3_url: 'http://eccube3/index_cover.php'
    include:
        - src/Eccube/*
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
    helpers: tests/_output
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    log: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
